# Name of your site (displayed in the header)
name: Calc Notes

# Short bio or description (displayed in the header)
description: Notes on single variable calculus.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: avatar: http://images.cdn4.stockunlimited.net/clipart/calculus-textbook_1547846.jpg
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

# Build settings
kramdown:
  input: GFM
permalink: pretty
