# Name of your site (displayed in the header)
name: Ctrl+V

# Short bio or description (displayed in the header)
description: Web Developer from Somewhere

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.i2clipart.com/cliparts/0/b/7/a/clipart-glue-0b7a.png
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
